use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct Preset {
    pub name: &'static str,
    pub description: &'static str,
    pub video_codec: &'static str,
    pub audio_codec: &'static str,
    pub container: &'static str,
    pub width: Option<u32>,
    pub height: Option<u32>,
    pub aspect: Option<&'static str>,
    pub crf: u8,
    pub notes: &'static [&'static str],
}

pub fn builtins() -> Vec<Preset> {
    vec![
        Preset {
            name: "tiktok",
            description: "Vertical creator export for TikTok.",
            video_codec: "libx264",
            audio_codec: "aac",
            container: "mp4",
            width: Some(1080),
            height: Some(1920),
            aspect: Some("9:16"),
            crf: 23,
            notes: &["Burned captions encouraged", "Faststart MP4"],
        },
        Preset {
            name: "reels",
            description: "Vertical Instagram Reels export.",
            video_codec: "libx264",
            audio_codec: "aac",
            container: "mp4",
            width: Some(1080),
            height: Some(1920),
            aspect: Some("9:16"),
            crf: 23,
            notes: &["Matches tiktok defaults", "Faststart MP4"],
        },
        Preset {
            name: "social",
            description: "General vertical social export.",
            video_codec: "libx264",
            audio_codec: "aac",
            container: "mp4",
            width: Some(1080),
            height: Some(1920),
            aspect: Some("9:16"),
            crf: 23,
            notes: &[
                "Alias-friendly creator preset",
                "Works for short-form video",
            ],
        },
        Preset {
            name: "youtube",
            description: "Standard YouTube upload.",
            video_codec: "libx264",
            audio_codec: "aac",
            container: "mp4",
            width: Some(1920),
            height: Some(1080),
            aspect: Some("16:9"),
            crf: 21,
            notes: &["Preserve stereo", "Good quality default"],
        },
        Preset {
            name: "youtube-short",
            description: "YouTube Shorts vertical export.",
            video_codec: "libx264",
            audio_codec: "aac",
            container: "mp4",
            width: Some(1080),
            height: Some(1920),
            aspect: Some("9:16"),
            crf: 23,
            notes: &["Shorts-safe aspect", "Faststart MP4"],
        },
        Preset {
            name: "podcast",
            description: "Clean spoken-word audio.",
            video_codec: "copy",
            audio_codec: "libmp3lame",
            container: "mp3",
            width: None,
            height: None,
            aspect: None,
            crf: 0,
            notes: &["Normalize audio", "Mono-friendly"],
        },
        Preset {
            name: "lecture",
            description: "Readable screen recording or class capture.",
            video_codec: "libx264",
            audio_codec: "aac",
            container: "mp4",
            width: Some(1920),
            height: Some(1080),
            aspect: Some("16:9"),
            crf: 24,
            notes: &["Smaller files", "Transcript-ready"],
        },
        Preset {
            name: "discord",
            description: "Small file export for chat sharing.",
            video_codec: "libx264",
            audio_codec: "aac",
            container: "mp4",
            width: Some(1280),
            height: Some(720),
            aspect: Some("16:9"),
            crf: 28,
            notes: &["Aggressive compression", "Broad compatibility"],
        },
        Preset {
            name: "web",
            description: "Web-friendly MP4/WebP defaults.",
            video_codec: "libx264",
            audio_codec: "aac",
            container: "mp4",
            width: Some(1280),
            height: None,
            aspect: None,
            crf: 25,
            notes: &["Progressive playback", "Reasonable size"],
        },
        Preset {
            name: "archive",
            description: "Conservative archival remux/copy preference.",
            video_codec: "copy",
            audio_codec: "copy",
            container: "mkv",
            width: None,
            height: None,
            aspect: None,
            crf: 0,
            notes: &["Prefer stream copy", "Keeps tracks"],
        },
    ]
}

pub fn find(name: &str) -> Option<Preset> {
    builtins().into_iter().find(|preset| preset.name == name)
}
